/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import datas._

case class Aeropuerto(Cod: String, X: Int, Y: Int, GMT: Double)

case class Vuelo(Airline: String, FlightNumber: Int, AirportOrigin: String, HS: Int, MS: Int, AirportDestination: String, HL: Int, ML: Int, Scales: Int)

case class Itinerario(vuelos: List[Vuelo], tiempoTotal: Int, escalas: Int, tiempoVuelo: Int)


object App {
  def main(args: Array[String]): Unit = {
    val benchmark = new ScheduleBenchmark()
    //benchmark.run(benchmark.benchmarkSchedulesSeq)(benchmark.benchmarkSchedulesPar)
    //benchmark.run(benchmark.benchmarkSchedulesTimeSeq)(benchmark.benchmarkSchedulesTimePar)
    //benchmark.run(benchmark.benchmarkSchedulesScalesSeq)(benchmark.benchmarkSchedulesScalesPar)
    //benchmark.run(benchmark.benchmarkSchedulesTimeLandSeq)(benchmark.benchmarkSchedulesTimeLandPar)
    benchmark.run(benchmark.benchmarkSchedulesOutputTimeSeq)(benchmark.benchmarkSchedulesOutputTimePar)
  }
}
